# Generated by Django 5.2.8 on 2025-11-08 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip_tracking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='requestlog',
            name='ip_address',
            field=models.CharField(max_length=50),
        ),
    ]
